// Client-safe status constants — no Prisma imports

export type TaskStatusType =
  | "DRAFT" | "PENDING_APPROVAL" | "APPROVED_AWAITING_TEAM" | "ACCEPTED_BY_TEAM"
  | "IN_ANALYSIS" | "IN_DEVELOPMENT" | "IN_TESTING" | "DEPLOYED"
  | "COORDINATOR_ACCEPTED" | "ACCEPTED_CLOSED" | "REWORK" | "REJECTED_BY_TEAM"
  | "PAUSED" | "KILLED";

export type RoleType =
  | "ADMIN" | "PRO_RECTOR" | "DIRECTOR" | "COORDINATOR" | "TEAM_RESOURCE";

export const VALID_TRANSITIONS: Record<TaskStatusType, TaskStatusType[]> = {
  DRAFT:                  ["PENDING_APPROVAL", "KILLED"],
  PENDING_APPROVAL:       ["APPROVED_AWAITING_TEAM", "DRAFT", "KILLED"],
  APPROVED_AWAITING_TEAM: ["ACCEPTED_BY_TEAM", "REJECTED_BY_TEAM", "PAUSED", "KILLED"],
  ACCEPTED_BY_TEAM:       ["IN_ANALYSIS", "PAUSED", "KILLED"],
  IN_ANALYSIS:            ["IN_DEVELOPMENT", "PAUSED", "KILLED"],
  IN_DEVELOPMENT:         ["IN_TESTING", "PAUSED", "KILLED"],
  IN_TESTING:             ["DEPLOYED", "IN_DEVELOPMENT", "PAUSED", "KILLED"],
  DEPLOYED:               ["COORDINATOR_ACCEPTED", "REWORK", "PAUSED", "KILLED"],
  COORDINATOR_ACCEPTED:   ["ACCEPTED_CLOSED", "REWORK", "KILLED"],
  REWORK:                 ["IN_DEVELOPMENT", "PAUSED", "KILLED"],
  REJECTED_BY_TEAM:       ["DRAFT", "KILLED"],
  PAUSED:                 ["KILLED"],
  ACCEPTED_CLOSED:        [],
  KILLED:                 [],
};

export const STATUS_ROLE_PERMISSIONS: Record<TaskStatusType, Partial<Record<TaskStatusType, RoleType[]>>> = {
  DRAFT: {
    PENDING_APPROVAL: ["COORDINATOR"],
    KILLED: ["COORDINATOR", "DIRECTOR", "PRO_RECTOR"],
  },
  PENDING_APPROVAL: {
    APPROVED_AWAITING_TEAM: ["DIRECTOR"],
    DRAFT: ["DIRECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  APPROVED_AWAITING_TEAM: {
    ACCEPTED_BY_TEAM: ["TEAM_RESOURCE"],
    REJECTED_BY_TEAM: ["TEAM_RESOURCE"],
    PAUSED: ["TEAM_RESOURCE", "DIRECTOR", "PRO_RECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  ACCEPTED_BY_TEAM: {
    IN_ANALYSIS: ["TEAM_RESOURCE"],
    PAUSED: ["TEAM_RESOURCE", "DIRECTOR", "PRO_RECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  IN_ANALYSIS: {
    IN_DEVELOPMENT: ["TEAM_RESOURCE"],
    PAUSED: ["TEAM_RESOURCE", "DIRECTOR", "PRO_RECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  IN_DEVELOPMENT: {
    IN_TESTING: ["TEAM_RESOURCE"],
    PAUSED: ["TEAM_RESOURCE", "DIRECTOR", "PRO_RECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  IN_TESTING: {
    DEPLOYED: ["TEAM_RESOURCE"],
    IN_DEVELOPMENT: ["TEAM_RESOURCE"],
    PAUSED: ["TEAM_RESOURCE", "DIRECTOR", "PRO_RECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  DEPLOYED: {
    COORDINATOR_ACCEPTED: ["COORDINATOR"],
    REWORK: ["COORDINATOR", "DIRECTOR"],
    PAUSED: ["COORDINATOR", "DIRECTOR", "PRO_RECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  COORDINATOR_ACCEPTED: {
    ACCEPTED_CLOSED: ["DIRECTOR"],
    REWORK: ["DIRECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  REWORK: {
    IN_DEVELOPMENT: ["TEAM_RESOURCE"],
    PAUSED: ["TEAM_RESOURCE", "DIRECTOR", "PRO_RECTOR"],
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  REJECTED_BY_TEAM: {
    DRAFT: ["COORDINATOR"],
    KILLED: ["COORDINATOR", "DIRECTOR", "PRO_RECTOR"],
  },
  PAUSED: {
    KILLED: ["DIRECTOR", "PRO_RECTOR"],
  },
  ACCEPTED_CLOSED: {},
  KILLED: {},
};

export const REQUEST_TYPES = [
  { value: "NEW_DEVELOPMENT", label: "New Development" },
  { value: "ENHANCEMENT", label: "Enhancement" },
  { value: "BUG_FIX", label: "Bug Fix" },
  { value: "POLICY_CHANGE", label: "Policy Change" },
] as const;

export const PRIORITIES = [
  { value: "CRITICAL", label: "Critical" },
  { value: "HIGH", label: "High" },
  { value: "MEDIUM", label: "Medium" },
  { value: "LOW", label: "Low" },
] as const;
