export const USERS = {
  proRector: {
    id: "user-001",
    name: "Pro Rector Academics",
    role: "prorector",
  },
  directorAcad: {
    id: "user-002",
    name: "Director ACAD",
    role: "director",
  },
  coordinators: [
    { id: "user-003", name: "Asst. Prof. Ahmed", role: "coordinator" },
    { id: "user-004", name: "Dr. Sana", role: "coordinator" },
  ],
  ictResources: [
    { id: "user-005", name: "Engr. Farooq", role: "ict" },
    { id: "user-006", name: "Engr. Ali", role: "ict" },
    { id: "user-007", name: "Engr. Bilal", role: "ict" },
  ],
};

export const TASKS = [
  {
    id: "AOT-001",
    title: "Automate School Data Collection Portal",
    type: "New Development",
    status: "In Development",
    priority: "Critical",
    description: "Build a portal for automated data collection from 15 affiliated schools. Currently done via email which takes 7 days per cycle.",
    affectedProcess: "School Data Collection",
    coordinator: "Asst. Prof. Ahmed",
    coordinatorId: "user-003",
    ict: "Engr. Farooq",
    ictId: "user-005",
    expectedDate: "2026-04-20",
    ictDate: "2026-04-28",
    toleranceDays: 7,
    preAutomationEffort: { value: 7, unit: "days" },
    postAutomationEffort: { value: 1, unit: "days" },
    policyReference: "",
    rejections: 0,
    lastActivity: "2026-04-08",
    daysOverdue: 0,
    acceptanceCriteria: [
      { id: "ac-1", text: "Data collected from all 15 schools within 24 hours", done: true },
      { id: "ac-2", text: "Auto-validation of submitted forms", done: true },
      { id: "ac-3", text: "Export to Excel with standardized format", done: false },
      { id: "ac-4", text: "Email notifications to school focal persons", done: false },
    ],
    documents: [
      { name: "Requirements Document v1.2.pdf", status: "Approved", uploadedBy: "Asst. Prof. Ahmed", uploadedAt: "2026-04-03" },
      { name: "Data Collection SOP.pdf", status: "Uploaded", uploadedBy: "Asst. Prof. Ahmed", uploadedAt: "2026-04-04" },
    ],
    createdAt: "2026-04-03T09:30:00Z",
  },
  {
    id: "AOT-002",
    title: "Fee Structure Policy Update Module",
    type: "Policy Change",
    status: "Pending Approval",
    priority: "High",
    description: "Update the fee management module to reflect the new fee structure policy effective Fall 2026. Requires changes to calculation engine and student portal display.",
    affectedProcess: "Fee Management",
    coordinator: "Dr. Sana",
    coordinatorId: "user-004",
    ict: "Engr. Ali",
    ictId: "user-006",
    expectedDate: "2026-05-01",
    ictDate: null,
    toleranceDays: 7,
    preAutomationEffort: { value: 3, unit: "days" },
    postAutomationEffort: { value: 0.5, unit: "days" },
    policyReference: "Policy Circular 2026-14",
    rejections: 0,
    lastActivity: "2026-04-09",
    daysOverdue: 0,
    acceptanceCriteria: [
      { id: "ac-1", text: "New fee slabs reflected in student portal", done: false },
      { id: "ac-2", text: "Scholarship discount logic updated", done: false },
      { id: "ac-3", text: "Challan generation with new amounts", done: false },
    ],
    documents: [
      { name: "Requirements_FeeUpdate.pdf", status: "Uploaded", uploadedBy: "Dr. Sana", uploadedAt: "2026-04-08" },
      { name: "Policy_Circular_2026-14.pdf", status: "Uploaded", uploadedBy: "Dr. Sana", uploadedAt: "2026-04-08" },
    ],
    createdAt: "2026-04-07T14:00:00Z",
  },
  {
    id: "AOT-003",
    title: "Exam Schedule Generator Bug Fix",
    type: "Bug Fix",
    status: "Rework",
    priority: "High",
    description: "Exam schedule generator produces overlapping time slots for multi-section courses. Affects all departments.",
    affectedProcess: "Examination Management",
    coordinator: "Asst. Prof. Ahmed",
    coordinatorId: "user-003",
    ict: "Engr. Bilal",
    ictId: "user-007",
    expectedDate: "2026-04-05",
    ictDate: "2026-04-10",
    toleranceDays: 3,
    preAutomationEffort: null,
    postAutomationEffort: null,
    policyReference: "",
    rejections: 3,
    lastActivity: "2026-04-02",
    daysOverdue: 4,
    acceptanceCriteria: [
      { id: "ac-1", text: "No overlapping slots for any department", done: false },
      { id: "ac-2", text: "Room assignments unique per time slot", done: false },
      { id: "ac-3", text: "Multi-section courses scheduled in parallel rooms", done: false },
    ],
    documents: [
      { name: "Bug_Report_ExamSchedule.pdf", status: "Approved", uploadedBy: "Asst. Prof. Ahmed", uploadedAt: "2026-03-28" },
    ],
    createdAt: "2026-03-27T10:00:00Z",
  },
  {
    id: "AOT-004",
    title: "Student Transcript Automation",
    type: "New Development",
    status: "Deployed",
    priority: "Medium",
    description: "Automate transcript generation from examination records. Currently takes 5 days for batch processing.",
    affectedProcess: "Transcript Issuance",
    coordinator: "Dr. Sana",
    coordinatorId: "user-004",
    ict: "Engr. Farooq",
    ictId: "user-005",
    expectedDate: "2026-03-30",
    ictDate: "2026-03-28",
    toleranceDays: 5,
    preAutomationEffort: { value: 5, unit: "days" },
    postAutomationEffort: { value: 0.5, unit: "days" },
    policyReference: "",
    rejections: 0,
    lastActivity: "2026-04-07",
    daysOverdue: 0,
    acceptanceCriteria: [
      { id: "ac-1", text: "Transcript generated within 30 seconds per student", done: true },
      { id: "ac-2", text: "Watermark and official header included", done: true },
      { id: "ac-3", text: "Batch processing for entire department in under 10 minutes", done: true },
      { id: "ac-4", text: "PDF download with QR verification code", done: true },
    ],
    documents: [
      { name: "Requirements_Transcript.pdf", status: "Approved", uploadedBy: "Dr. Sana", uploadedAt: "2026-03-10" },
      { name: "Transcript_Template_Specs.pdf", status: "Approved", uploadedBy: "Dr. Sana", uploadedAt: "2026-03-11" },
    ],
    createdAt: "2026-03-08T11:00:00Z",
  },
  {
    id: "AOT-005",
    title: "Faculty Workload Dashboard Enhancement",
    type: "Enhancement",
    status: "In Analysis",
    priority: "Medium",
    description: "Add visualization layer to existing faculty workload module. Show credit hour distribution, research supervision load, and committee assignments.",
    affectedProcess: "Faculty Management",
    coordinator: "Asst. Prof. Ahmed",
    coordinatorId: "user-003",
    ict: "Engr. Ali",
    ictId: "user-006",
    expectedDate: "2026-05-15",
    ictDate: "2026-05-20",
    toleranceDays: 7,
    preAutomationEffort: { value: 2, unit: "days" },
    postAutomationEffort: { value: 0.25, unit: "days" },
    policyReference: "",
    rejections: 0,
    lastActivity: "2026-04-06",
    daysOverdue: 0,
    acceptanceCriteria: [
      { id: "ac-1", text: "Dashboard shows per-faculty credit hour breakdown", done: false },
      { id: "ac-2", text: "Research supervision count visible", done: false },
      { id: "ac-3", text: "Export to PDF for HOD review", done: false },
    ],
    documents: [
      { name: "Requirements_WorkloadDashboard.pdf", status: "Approved", uploadedBy: "Asst. Prof. Ahmed", uploadedAt: "2026-04-01" },
    ],
    createdAt: "2026-03-30T09:00:00Z",
  },
  {
    id: "AOT-006",
    title: "Online Admission Portal v2",
    type: "New Development",
    status: "Accepted - Closed",
    priority: "Critical",
    description: "Complete redesign of admission portal with merit calculation, document verification, and fee payment integration.",
    affectedProcess: "Student Admissions",
    coordinator: "Dr. Sana",
    coordinatorId: "user-004",
    ict: "Engr. Bilal",
    ictId: "user-007",
    expectedDate: "2026-03-15",
    ictDate: "2026-03-14",
    toleranceDays: 5,
    preAutomationEffort: { value: 14, unit: "days" },
    postAutomationEffort: { value: 2, unit: "days" },
    policyReference: "Admission Policy 2026",
    rejections: 1,
    lastActivity: "2026-03-20",
    daysOverdue: 0,
    acceptanceCriteria: [
      { id: "ac-1", text: "Online application form with document upload", done: true },
      { id: "ac-2", text: "Automatic merit calculation", done: true },
      { id: "ac-3", text: "Online fee payment via JazzCash/Easypaisa", done: true },
      { id: "ac-4", text: "Applicant dashboard with status tracking", done: true },
    ],
    documents: [
      { name: "Requirements_AdmissionPortal_v2.pdf", status: "Approved", uploadedBy: "Dr. Sana", uploadedAt: "2026-02-15" },
      { name: "Admission_Policy_2026.pdf", status: "Approved", uploadedBy: "Dr. Sana", uploadedAt: "2026-02-15" },
    ],
    createdAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "AOT-007",
    title: "Attendance Integration with LMS",
    type: "Enhancement",
    status: "Paused",
    priority: "Low",
    description: "Integrate biometric attendance system with LMS for automatic attendance marking. Paused due to LMS vendor contract renegotiation.",
    affectedProcess: "Attendance Management",
    coordinator: "Asst. Prof. Ahmed",
    coordinatorId: "user-003",
    ict: "Engr. Farooq",
    ictId: "user-005",
    expectedDate: "2026-06-01",
    ictDate: null,
    toleranceDays: 10,
    preAutomationEffort: { value: 1, unit: "days" },
    postAutomationEffort: { value: 0.1, unit: "days" },
    policyReference: "",
    rejections: 0,
    lastActivity: "2026-03-25",
    daysOverdue: 0,
    acceptanceCriteria: [
      { id: "ac-1", text: "Biometric data synced with LMS within 5 minutes", done: false },
      { id: "ac-2", text: "Attendance discrepancy alerts to faculty", done: false },
    ],
    documents: [
      { name: "Requirements_AttendanceLMS.pdf", status: "Approved", uploadedBy: "Asst. Prof. Ahmed", uploadedAt: "2026-03-15" },
    ],
    createdAt: "2026-03-12T08:30:00Z",
  },
  {
    id: "AOT-008",
    title: "Semester Registration Workflow Digitization",
    type: "New Development",
    status: "Approved - Awaiting ICT",
    priority: "High",
    description: "Digitize the entire semester registration process including course selection, advisor approval, fee clearance, and final enrollment.",
    affectedProcess: "Semester Registration",
    coordinator: "Dr. Sana",
    coordinatorId: "user-004",
    ict: "Engr. Ali",
    ictId: "user-006",
    expectedDate: "2026-05-10",
    ictDate: null,
    toleranceDays: 7,
    preAutomationEffort: { value: 10, unit: "days" },
    postAutomationEffort: { value: 1, unit: "days" },
    policyReference: "Registration Policy 2025-R3",
    rejections: 0,
    lastActivity: "2026-04-04",
    daysOverdue: 0,
    acceptanceCriteria: [
      { id: "ac-1", text: "Student can select courses online", done: false },
      { id: "ac-2", text: "Advisor approval workflow with notifications", done: false },
      { id: "ac-3", text: "Fee clearance check automated", done: false },
      { id: "ac-4", text: "Enrollment confirmation email with timetable", done: false },
    ],
    documents: [
      { name: "Requirements_SemRegistration.pdf", status: "Approved", uploadedBy: "Dr. Sana", uploadedAt: "2026-04-01" },
      { name: "Registration_Policy_2025-R3.pdf", status: "Approved", uploadedBy: "Dr. Sana", uploadedAt: "2026-04-01" },
    ],
    createdAt: "2026-03-28T13:00:00Z",
  },
];

export const NOTIFICATIONS = [
  {
    id: 1,
    type: "critical",
    taskId: "AOT-003",
    text: "AOT-003 rejected 3 times. Auto-escalated to Pro Rector.",
    time: "2026-04-09T07:00:00Z",
    timeLabel: "2 hours ago",
    read: false,
  },
  {
    id: 2,
    type: "danger",
    taskId: "AOT-003",
    text: "AOT-003 (Exam Schedule Generator) is 4 days overdue.",
    time: "2026-04-09T06:00:00Z",
    timeLabel: "3 hours ago",
    read: false,
  },
  {
    id: 3,
    type: "warning",
    taskId: "AOT-008",
    text: "AOT-008 has had no activity for 5 days. Escalated.",
    time: "2026-04-09T04:00:00Z",
    timeLabel: "5 hours ago",
    read: false,
  },
  {
    id: 4,
    type: "info",
    taskId: "AOT-004",
    text: "AOT-004 (Transcript Automation) deployed, awaiting your sign-off.",
    time: "2026-04-08T10:00:00Z",
    timeLabel: "1 day ago",
    read: true,
  },
  {
    id: 5,
    type: "info",
    taskId: "AOT-002",
    text: "AOT-002 (Fee Structure Update) submitted for Director approval.",
    time: "2026-04-08T08:00:00Z",
    timeLabel: "1 day ago",
    read: true,
  },
];

export const CHAT_MESSAGES = {
  "AOT-003": [
    {
      id: "msg-1",
      role: "coordinator",
      name: "Asst. Prof. Ahmed",
      text: "The exam schedule bug is affecting all departments. Students are seeing wrong dates for multi-section courses.",
      time: "2026-04-02T10:15:00Z",
      timeLabel: "Apr 2, 10:15 AM",
    },
    {
      id: "msg-2",
      role: "ict",
      name: "Engr. Bilal",
      text: "Fixed the date parsing logic. Deployed to staging for testing.",
      time: "2026-04-03T14:30:00Z",
      timeLabel: "Apr 3, 2:30 PM",
    },
    {
      id: "msg-3",
      role: "coordinator",
      name: "Asst. Prof. Ahmed",
      text: "Tested on staging. The overlap detection is still broken for multi-section courses. CS-201 and CS-201L both show Room 5 at 10 AM.",
      time: "2026-04-04T09:00:00Z",
      timeLabel: "Apr 4, 9:00 AM",
    },
    {
      id: "msg-4",
      role: "director",
      name: "Director ACAD",
      text: "This is critical. The Academic Council meeting is next week and we need the exam schedule finalized before that.",
      time: "2026-04-05T11:00:00Z",
      timeLabel: "Apr 5, 11:00 AM",
    },
    {
      id: "msg-5",
      role: "ict",
      name: "Engr. Bilal",
      text: "Understood. Reworking the overlap detection algorithm from scratch. Will need 2 more days.",
      time: "2026-04-05T15:00:00Z",
      timeLabel: "Apr 5, 3:00 PM",
    },
    {
      id: "msg-6",
      role: "coordinator",
      name: "Asst. Prof. Ahmed",
      text: "Tested the third deployment. Time slots are now correct but room assignments are duplicating across departments. EE and ME both assigned Room 12 at the same time.",
      time: "2026-04-07T10:00:00Z",
      timeLabel: "Apr 7, 10:00 AM",
    },
  ],
  "AOT-001": [
    {
      id: "msg-1",
      role: "coordinator",
      name: "Asst. Prof. Ahmed",
      text: "The data collection form should support both English and Urdu input for school names.",
      time: "2026-04-04T11:00:00Z",
      timeLabel: "Apr 4, 11:00 AM",
    },
    {
      id: "msg-2",
      role: "ict",
      name: "Engr. Farooq",
      text: "Noted. Adding bilingual support. Will this apply to all fields or just school name?",
      time: "2026-04-05T09:30:00Z",
      timeLabel: "Apr 5, 9:30 AM",
    },
    {
      id: "msg-3",
      role: "coordinator",
      name: "Asst. Prof. Ahmed",
      text: "School name and address fields. The rest can be English only.",
      time: "2026-04-05T10:00:00Z",
      timeLabel: "Apr 5, 10:00 AM",
    },
  ],
};

export const AUDIT_LOGS = {
  "AOT-001": [
    { action: "Status changed to In Development", by: "Engr. Farooq", role: "ICT", time: "Apr 8, 2:30 PM" },
    { action: "Accepted by ICT. Estimate: Apr 28", by: "Engr. Farooq", role: "ICT", time: "Apr 6, 10:00 AM" },
    { action: "Approved by Director ACAD", by: "Director ACAD", role: "Director", time: "Apr 5, 4:00 PM" },
    { action: "Documents verified and approved", by: "Director ACAD", role: "Director", time: "Apr 5, 3:45 PM" },
    { action: "Task submitted for approval", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Apr 4, 11:00 AM" },
    { action: "Requirements Document uploaded", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Apr 3, 10:00 AM" },
    { action: "Task created", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Apr 3, 9:30 AM" },
  ],
  "AOT-003": [
    { action: "Auto-escalated to Pro Rector (3rd rejection)", by: "System", role: "System", time: "Apr 9, 7:00 AM" },
    { action: "Status changed to Rework (3rd time)", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Apr 7, 10:30 AM" },
    { action: "Deliverable rejected: room duplication bug", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Apr 7, 10:15 AM" },
    { action: "Status changed to Deployed", by: "Engr. Bilal", role: "ICT", time: "Apr 6, 5:00 PM" },
    { action: "Status changed to Rework (2nd time)", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Apr 4, 9:30 AM" },
    { action: "Deliverable rejected: overlap not fixed", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Apr 4, 9:15 AM" },
    { action: "Status changed to Deployed", by: "Engr. Bilal", role: "ICT", time: "Apr 3, 3:00 PM" },
    { action: "Status changed to Rework (1st time)", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Apr 1, 11:00 AM" },
    { action: "Task created", by: "Asst. Prof. Ahmed", role: "Coordinator", time: "Mar 27, 10:00 AM" },
  ],
};
